# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-19 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriberuser',
            name='is_follow',
            field=models.BooleanField(default=True, verbose_name='is follow?'),
        ),
    ]
